# docker-compose.yml
version: "3"
services:
  db:
    image: "postgres:11.4"
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER"
      - "POSTGRES_PASSWORD"
      - "POSTGRES_DB"
  app:
    build: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "db:5432",
        "--",
        "python3",
        "manage.py",
        "runserver",
        "0.0.0.0:8000",
      ]
    volumes:
      - "./project:/usr/src/app/myproject"
      - "./apps/external:/usr/src/app/external"
      - "./apps/myapp1:/usr/src/app/myapp1"
      - "./apps/myapp2:/usr/src/app/myapp2"

    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    environment:
      - "SITE_HOST"
      - "POSTGRES_HOST=db"
      - "POSTGRES_USER"
      - "POSTGRES_PASSWORD"
      - "POSTGRES_DB"
